#!/usr/bin/env python3.10

from exceptions import ApiServiceError, CantGetCoordinates
from coords import get_gps_coordinates
from api_service import get_weather
from formatter import format_weather


def main():
    try:
        coordinates = get_gps_coordinates()
    except CantGetCoordinates:
        print("Не смог получить GPS-координаты")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except ApiServiceError:
        print("Не смог получить погоду в API-сервиса погоды")
        exit(1)
    print(format_weather(weather))


if __name__ == "__main__":
    main()
